### PR TITLE
Fix block-engine jwt refreshToken expiring

### LINKED ISSUE #10: SearcherClient should automatically fetch new auth headers
The interceptor which provides the auth expires after an hour. The SearcherClient doesn't automatically refetch new auth interceptors nor does it expose a function to pass in new auth parameters

### PR DESCRIPTION
**Pull request by futurekarol**
there is an issue where searcher client errors with `Error: 7 PERMISSION_DENIED: Client refresh_token has expired, please generate a new auth challenge to obtain a set of new access tokens.`

- added `refreshToken.isExpired()` check to `injectAccessToken`. if true, run the `fullAuth` flow to obtain a new one
- full auth somehow sets the refresh token to the response auth token. changed that to match

maybe this fixes #10 too

### CODE REVIEW

File: src/sdk/block-engine/auth.ts [hunk 1]
```diff
@@ -70,7 +70,11 @@ export class AuthProvider {
   // Injects the current access token into the provided callback.
   // If it's expired then refreshes, if the refresh token is expired then runs the full auth flow.
   public injectAccessToken(callback: (accessToken: Jwt) => void) {
-    if (!this.accessToken) {
+    if (
+      !this.accessToken ||
+      !this.refreshToken ||
+      this.refreshToken.isExpired()
```
Comment (segfaultdoc) [inline src/sdk/block-engine/auth.ts:76]: 👍

**Review by segfaultdoc — DISMISSED** [review]
